FROM ubuntu:focal

ENV VERSION=22.0
ENV ARCH=x86_64

RUN apt-get update

RUN apt-get -y install curl

RUN curl -OL https://bitcoin.org/bin/bitcoin-core-${VERSION}/bitcoin-${VERSION}-${ARCH}-linux-gnu.tar.gz

RUN tar zxvf bitcoin-${VERSION}-${ARCH}-linux-gnu.tar.gz

COPY bitcoin.conf /root/.bitcoin/bitcoin.conf
COPY start-node.sh /root

EXPOSE 18332

CMD ["sh","/root/start-node.sh"]
